### ISSUE TITLE
Delete from array in "to String.vim" is missing an index input

### ISSUE THREAD

**Issue by Miles-git** [approvals/ApprovalTests.LabVIEW#1]
The delete from array in the "1D arrays of everything else" case of "lib_Approval Tests.lvlib:to String.vim" should have a 0 wired into the index input:
![image](https://github.com/approvals/ApprovalTests.LabVIEW/assets/172388511/b0551f2b-22a6-4ccb-bd2a-5be06b0af164)

Currently it is removing the last element instead of the first and so the array in the log string is in the incorrect order.

**Comment by stagg54** [comment]
Good catch.

**Comment by stagg54** [comment]
See if this fixes your problem. If so, let me know and I'll release it on VIPM. If you give me your VIPM Id, I'll tag you as a contributor.
[Approvals 2.2.2.zip](https://github.com/user-attachments/files/15890228/Approvals.2.2.2.zip)

**Comment by Miles-git** [comment]
Yes that fixes the issue.  Thanks for the fast turnaround.  My VIPM Id is miles_vipm

**Comment by stagg54** [comment]
fixed in 2.2.2
