### ISSUE TITLE
Test Labels don't work in Caraya

### ISSUE THREAD

**Issue by phorn-NI** [approvals/ApprovalTests.LabVIEW#3]
I've got a test that has multiple scenarios to test the vi under test against, and have a different label for each (this was previously a standard Caraya unit test where I built the expected maps on the test block diagram - that was passing so I know the vi is correct currently - I'm planning to remove the timestamp input as that is only there for the test so I can pass in a constant timestamp, I'll remove it and add a scrubber once the test is working).

The VI is called Test LLD Update.vi

![image](https://github.com/user-attachments/assets/ac38d431-5ee2-40c7-b280-fbf0b5d2cc36)

So I'd expect there to be 3 approved files created:

- Test LLD Update.Add to empty map - timestamp updated.approved.txt
- Test LLD Update.Add to existing map - timestamp updated.approved.txt
- Test LLD Update.Add to existing map, no change values means no update.approved.txt

But instead I just get Test LLD Update.approved.txt

![image](https://github.com/user-attachments/assets/e4c0fae2-403a-4f24-b056-ac12d04812a0)

I can see in a probe that there is 2 places where the Test VI Name and Test Label can be stored in the class - is it going into the correct one? I don't have an accessor to put it into the Namer.lvclass data

![image](https://github.com/user-attachments/assets/7bce946f-8328-4458-8faf-f9d7d014b14a)

Am I doing something wrong?

**Comment by stagg54** [comment]
You aren't doing anything wrong. That is exactly what is intended, except that I haven't fully implemented it yet. It is on the roadmap and I haven't gotten around to it yet. I just recently started working on it. Luckily for you I started implementing it in Caraya first.

Try downloading the artifacts from here: https://github.com/approvals/ApprovalTests.LabVIEW/actions/runs/10926173797
They are at the bottom of the page.

Install that package and in the Caraya extension you should see another optional input next to the Options cluster called "Label". Wire that with your test label and you should see the behaviour you are looking for. No need to do all those objects and property nodes.

Let me know if that works for you. If it does, then I'll implement it in the other extensions and make a new release.

**Comment by stagg54** [comment]
I found a little time and added support for the other extensions - it didn't take long. Let me know if that works and I'll make a release.

**Comment by phorn-NI** [comment]
Quick again! 👍 

Yep, that works - my only comment would be that the test label should overwrite the default name of "Verify" - as my Results don't tell me which has passed/failed
![image](https://github.com/user-attachments/assets/6eb38d75-c25b-48ea-a573-57913ea28354)

**Comment by stagg54** [comment]
ah. Well let me see what I can do with that. I don't think I'll get a build out today. My CI server is not working because VIPM is down at the moment. Once it comes back up I'll get you another build.

**Comment by phorn-NI** [comment]
Yeah, I noticed VIPM was down - bit of a pain.... No worries

**Comment by stagg54** [comment]
Jim and Company are aware, so it'll get resolved as soon as it gets resolved.

**Comment by stagg54** [comment]
Resolved in 2.2.6 release on VIPM.
